# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true 
# ~/.config/starship.toml

[character]
#vimcmd_symbol = '[‚ùÆ](bold purple)'
vimcmd_symbol = '[V](bold purple)'

[gcloud]
disabled = false 
format = "on [$symbol($project)](bold yellow) as $symbol[$account](bold blue) "

[custom.gcp_adc]
when = "test -f ~/.config/gcloud/application_default_credentials.json"
command = "jq -r '.type // empty' ~/.config/gcloud/application_default_credentials.json"
format = "[ADC: $output ](bold green)"
disabled = false

[aws]
disabled = true 
