# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true 
# ~/.config/starship.toml

[character]
#vimcmd_symbol = '[‚ùÆ](bold purple)'
vimcmd_symbol = '[V](bold purple)'

